### ISSUE TITLE
复刻抽出来的图像会有细节偏差

### ISSUE THREAD

**Issue by AyasakiAtre** [sdbds/stable-diffusion-webui-wildcards#2]
![original1](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/b2ab9c38-5b49-44fa-b854-4bfd9318b0a0)
![image](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/ffca1e46-02bf-4c71-b304-b5b55d5c2798)
这张是原图
![reprint1](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/c23c2dc9-cb72-4b03-8801-d856d3793a3f)
![image](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/e6d558c7-6253-4170-87ad-3133a8a162fe)
这张是复刻

下面是更多对比
![original](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/3493208d-1ec9-4c13-833a-2f40e45f8603)
![reprint](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/f8abc9fb-25d4-4353-834c-397b1bc7719e)
![original2](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/5c797ef9-7359-4fd9-8332-d5f25254193a)
![reprint2](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/a6feb3c7-3447-4f6b-a7c8-86c73b09643a)

我发现只要使用wildcard抽出来的，都会这样，不带wildcard的就可以完美复刻，请问青龙佬这是什么问题呢

**Comment by sdbds** [comment]
细节偏差是因为显卡型号和xformers内存优化造成的。关闭xformers使用no nem SDP实验一下.

**Comment by AyasakiAtre** [comment]
> 细节偏差是因为显卡型号和xformers内存优化造成的。关闭xformers使用no nem SDP实验一下.

感谢回复，我关闭xf后继续实验了复刻，结果还是和我问题一样，无法复刻，使用no mem SDP也是一样。
![image](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/861c6142-2df8-4e4e-893f-f0b181a02dc2)
这是关闭xf后使用wildcards抽卡的，6g显存只能这种分辨率了:(
![image](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/4346abce-f988-4f53-bd79-d063f8cb5abb)
这是复刻
我是直接使用图片信息发送到文生图进行生成的，不存在参数问题。
只要不用wildcards抽卡，我的出图基本都是可以复刻的，不知道青龙佬会不会这样呢？

**Comment by sdbds** [comment]
linux测试无法复现这个问题，建议关闭其他插件试一下。

**Comment by AyasakiAtre** [comment]
> 

感谢回复，我尝试一个一个的关闭插件，到最后的关闭全部插件，均出现这种细节偏差，不清楚到底是哪里的问题，或许我该重新部署一个SD进行尝试。

**Comment by AyasakiAtre** [comment]
> linux测试无法复现这个问题，建议关闭其他插件试一下。 ![image](https://user-images.githubusercontent.com/8085926/249050388-059ab215-4d1f-42ec-9915-a2a7f0a4417d.png) ![image](https://user-images.githubusercontent.com/8085926/249050397-5849c9c5-0abb-45f2-a2d3-412aa984f781.png)

感谢回复，我尝试一个一个的关闭插件，到最后的关闭全部插件，均出现这种细节偏差，不清楚到底是哪里的问题，或许我该重新部署一个SD进行尝试。

**Comment by AyasakiAtre** [comment]
> > linux测试无法复现这个问题，建议关闭其他插件试一下。 ![image](https://user-images.githubusercontent.com/8085926/249050388-059ab215-4d1f-42ec-9915-a2a7f0a4417d.png) ![image](https://user-images.githubusercontent.com/8085926/249050397-5849c9c5-0abb-45f2-a2d3-412aa984f781.png)
> 
> 感谢回复，我尝试一个一个的关闭插件，到最后的关闭全部插件，均出现这种细节偏差，不清楚到底是哪里的问题，或许我该重新部署一个SD进行尝试。

在重新部署了一个SD后，我设置了karras sigma为旧值，Eta31337和clip2后，仅安装了wildcards进行抽卡
![00001-1561140761](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/3e517a34-cf35-4cf5-b17f-d1a7bd0c131a)
![00002-1561140761](https://github.com/sdbds/stable-diffusion-webui-wildcards/assets/83602783/072ab6cb-0c85-4e9a-850b-2932d718fd2e)
仍然出现了这种问题，只要不使用wildcards就可以复刻出来。sad:(
