### ISSUE TITLE
__无法调用

### ISSUE THREAD

**Issue by figurehunt** [sdbds/stable-diffusion-webui-wildcards#5]
大佬好！今天发现双下横杠无法调用wildcards tag，因此按照页面安装提示操作，将旧的wildcards备份后卸载，也卸了after detailer，然后重装wildcards和ad，最后将备份的内容复制粘贴覆盖到本次新装的wildcards文件夹里面。然后重启发现，还是无法通过双下横杠调用wildcards tag。
我使用的是秋叶版本的SD，本体和扩展都是最新的了

请教一下应该怎么操作！感谢感谢！

**Comment by designrans** [comment]
同样的问题

**Comment by sdbds** [comment]
> 大佬好！今天发现双下横杠无法调用wildcards tag，因此按照页面安装提示操作，将旧的wildcards备份后卸载，也卸了after detailer，然后重装wildcards和ad，最后将备份的内容复制粘贴覆盖到本次新装的wildcards文件夹里面。然后重启发现，还是无法通过双下横杠调用wildcards tag。 我使用的是秋叶版本的SD，本体和扩展都是最新的了
> 
> 请教一下应该怎么操作！感谢感谢！

自动补全没更吗？

**Comment by figurehunt** [comment]
> > 大佬好！今天发现双下横杠无法调用wildcards tag，因此按照页面安装提示操作，将旧的wildcards备份后卸载，也卸了after detailer，然后重装wildcards和ad，最后将备份的内容复制粘贴覆盖到本次新装的wildcards文件夹里面。然后重启发现，还是无法通过双下横杠调用wildcards tag。 我使用的是秋叶版本的SD，本体和扩展都是最新的了
> > 请教一下应该怎么操作！感谢感谢！
> 
> 自动补全没更吗？

用的是秋叶整合包里默认的 a1111-sd-webui-tagcomplete，你是指这个吗？还是得装别的？装别的会否跟默认的这个冲突？
